Create events
petrukhinilya/Calendar pull request #11
Opened 2021-01-27 08:37 UTC by petrukhinilya

2021-01-27 10:06 UTC, d-lazarev requested changes
Please see my notes below

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Backend/controllers/events.js
> +            // const arr = events.map(x => x.startDate)
Why this code is commented on?

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Actions/index.js
> +      event: {body}
Enforce spacing inside of computed property brackets (https://github.com/airbnb/javascript#whitespace **19.16**)

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Actions/index.js
> +
Unnecessary skipped line

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Actions/index.js
> +    console.log(events)
Remove console.log

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Actions/index.js
> +      payload: {events}
Enforce spacing inside of computed property brackets (https://github.com/airbnb/javascript#whitespace 19.16)

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Actions/index.js
> +    console.log(e)
How the app will work if dispatch returns an error? Just print an error to the console?

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  // const [events, setEvents] = useState([]);
Why this code is commented on?

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const a = useSelector(state => state.events.events);
what is `a`???

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                }
103 - 107 fix alignment

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                const arr = createCalendar(day , a , dayStyles , setValue)
What is `arr`?

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
>  export default Calendar
No new line at the end of file

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +  const newArr = [];
What is `newArr`?

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +            }
18-23 fix alignment

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +  )
alignment

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +}
no newline at the end of file

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Popup.js
> +export default Popup;
No newline at the end of file

2021-01-27 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Popup.js
> +export default Popup;
Tabulation wasn't fixed in this file

2021-01-27 11:34 UTC, petrukhinilya reviewed
Fixed

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Backend/controllers/events.js
> +            // const arr = events.map(x => x.startDate)
It was hint for retrieve data
Fixed

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Actions/index.js
> +      event: {body}
Fixed

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Actions/index.js
> +
Fixed

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Actions/index.js
> +    console.log(events)
resolved

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  // const [events, setEvents] = useState([]);
I considered It would be useful in future features

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Actions/index.js
> +      payload: {events}
Resolved

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Actions/index.js
> +    console.log(e)
I made new case for handling such errors

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const a = useSelector(state => state.events.events);
a it`s data from redux which consists of arr of events

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                const arr = createCalendar(day , a , dayStyles , setValue)
It`s unnecessary (only for vusual)

Resolved

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +  const newArr = [];
newArr it`s array of events with data inside

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Popup.js
> +export default Popup;
Resolved

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +            }
Fixed

2021-01-27 11:34 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                }
Fixed

2021-01-27 11:35 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +}
Fixed

2021-01-27 11:45 UTC, d-lazarev requested changes
Please see my notes below

2021-01-27 11:45 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const a = useSelector(state => state.events.events);
about naming

2021-01-27 11:45 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                }
Wasn't fixed

2021-01-27 11:45 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  // const [events, setEvents] = useState([]);
ok

2021-01-27 11:45 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
>  export default Calendar
wasn't fixed

2021-01-27 11:45 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +  const newArr = [];
naming

2021-01-27 11:45 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +}
wasn't fixed

2021-01-27 11:45 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Popup.js
> +export default Popup;
wasn't fixed

2021-01-27 12:32 UTC, d-lazarev requested changes
See my notes

2021-01-27 12:32 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const arrOfEvents = useSelector(state => state.events.events);
don't use `arr` in naming variables or functions

2021-01-27 12:32 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +  const arrOfEvents = [];
Don't use `arr` in naming variables of functions

2021-01-27 13:42 UTC, d-lazarev requested changes
Notes

2021-01-27 13:42 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const getallEvents = useSelector(state => state.events.events);
Why this variable named `get...`?
This variable just store the events and it should be a `noun` 

I suppose we take data via function useSelector that`s why used get..

2021-01-27 14:33 UTC, d-lazarev requested changes
notes

2021-01-27 14:33 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const allEventsFromRedux = useSelector(state => state.events.events);
`allEventsFromRedux` -> `allEvents`

2021-01-28 08:04 UTC, d-lazarev approved these changes

2021-01-28 08:04 UTC, merged