Ability make events in each day from start to end
petrukhinilya/Calendar pull request #12
Opened 2021-01-28 14:20 UTC by petrukhinilya

2021-01-29 10:36 UTC, d-lazarev requested changes
Please, see my notes below

2021-01-29 10:36 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +            // console.log(event)
The consoles and commented code shouldn't be here
Also, if you don't do any modifications with data in the `map` callback, you can don't write a `return` word and just render with a round bracket

2021-01-29 10:36 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +        </div>
fix codestyle

2021-01-29 10:36 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +          }
fix codestyle

2021-01-29 11:00 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +            // console.log(event)
I belive that word Return will help me in future. I will modificate my data later.
Fixed

2021-01-29 11:05 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +          }
Fixed

2021-01-29 11:12 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +        </div>
Fixed, made divs in one line

2021-02-02 09:04 UTC, d-lazarev requested changes
See my notes

2021-02-02 09:04 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +          }
Was fixed not completely

Fixed , in next PR

2021-02-02 10:06 UTC, d-lazarev requested changes
Notes

2021-02-02 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +              }
Why these functions are presented in the `map` callback?

2021-02-02 10:06 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +          }
Should be fixed in this PR

2021-02-02 10:14 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +              }
When switched branch these files was added automatically

2021-02-02 10:40 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +              }
I have a lot of mistakes if relocate this functions cause funcs interacts this 'event' inside map

2021-02-02 12:50 UTC, d-lazarev requested changes
Notes

2021-02-02 12:50 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/ChangePopup.js
> +    } = e;
20 - 34  - Fix alignment

2021-02-02 12:50 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/ChangePopup.js
> +          </div>
Fix Alignment

2021-02-02 12:50 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/ChangePopup.js
> +            <input type='reset' onClick={onClick} className='reset'></input>
Use autoclosing for tags that don't have the body

2021-02-02 12:50 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +
Unnecessary to skip a line

2021-02-02 12:50 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +                <button className='del' >Del</button>
Fix codestyle

2021-02-02 12:50 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +          }
Still wasn't fixed

2021-02-02 12:50 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +    <div className='day' onClick={() => setValue(day)} >
fix codestyle

2021-02-02 12:57 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/ChangePopup.js
> +    } = e;
Fixed

2021-02-02 12:58 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/ChangePopup.js
> +            <input type='reset' onClick={onClick} className='reset'></input>
fixed

2021-02-02 12:59 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/ChangePopup.js
> +          </div>
Resolved

2021-02-02 13:04 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +
Fixed

2021-02-02 13:04 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +                <button className='del' >Del</button>
Fixed

2021-02-02 13:05 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +    <div className='day' onClick={() => setValue(day)} >
Fixed

2021-02-02 13:28 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +          }
Fixed

2021-02-02 13:32 UTC, d-lazarev approved these changes

2021-02-02 13:32 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/ChangePopup.js
> +export default ChangePopup;
No newline at end of file

2021-02-02 13:32 UTC, merged