Ability to Delete events
petrukhinilya/Calendar pull request #13
Opened 2021-02-01 07:37 UTC by petrukhinilya

2021-02-02 09:10 UTC, d-lazarev requested changes
See my notes

2021-02-02 09:10 UTC, d-lazarev commented on ProjectCalendar/Backend/controllers/events.js
> +        eventsModel.deleteOne({_id:req.params.id},function (err) {
Why are you mixing the code style? (camelCase and snake_case)

2021-02-02 09:10 UTC, d-lazarev commented on ProjectCalendar/Backend/routes/events.js
> +router.delete('/:id/deleteevent',event_controller.delete_event);
https://metamug.com/article/rest-api-naming-best-practices.html

2021-02-02 09:10 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +          }
FIx codestyle

2021-02-02 09:10 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                  return createCalendar(day, allEvents, dayStyles, setValue, deleteEvent)
Why is it a function and not a component?

2021-02-02 09:31 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +          }
Fixed

2021-02-02 10:06 UTC, petrukhinilya commented on ProjectCalendar/Backend/controllers/events.js
> +        eventsModel.deleteOne({_id:req.params.id},function (err) {
Cause didn`t get true sample of using code.
Fixed

2021-02-02 13:46 UTC, petrukhinilya commented on ProjectCalendar/Backend/routes/events.js
> +router.delete('/:id/deleteevent',event_controller.delete_event);
Fixed

2021-02-02 14:07 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                  return createCalendar(day, allEvents, dayStyles, setValue, deleteEvent)
Cause it`s more convenient to me use function. It`s necessary using component or just recommendation?

2021-02-02 14:34 UTC, d-lazarev requested changes

2021-02-02 14:34 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                  return createCalendar(day, allEvents, dayStyles, setValue, deleteEvent)
It's not a recommendation it should be a functional component and should be rendered as `<ComponentName ....... >`
A function that returns JSX shouldn't be named a verb

2021-02-02 14:34 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +            }
It's shouldn't be here, please move it from `map`

2021-02-02 14:34 UTC, d-lazarev commented on ProjectCalendar/Backend/controllers/events.js
> +        Events.create({ startDate: req.body.inputStartDate, endDate: req.body.inputEndDate, event: req.body.event, created_by: req.body.created_by }, function (err, result) {
Too long line, please destructure the `req.body` to make it shorter

2021-02-02 14:34 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +
Too many blank lines

2021-02-02 14:38 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +
Fixed

2021-02-02 15:01 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +            }
Fixed

2021-02-03 06:58 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +
Fixed

2021-02-03 06:58 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
> +            }
fixed

2021-02-03 07:52 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                  return createCalendar(day, allEvents, dayStyles, setValue, deleteEvent)
Fixed / New name for this component CalendarFormation

2021-02-03 08:10 UTC, petrukhinilya commented on ProjectCalendar/Backend/controllers/events.js
> +        Events.create({ startDate: req.body.inputStartDate, endDate: req.body.inputEndDate, event: req.body.event, created_by: req.body.created_by }, function (err, result) {
Fixed

2021-02-03 09:07 UTC, d-lazarev requested changes
Notes

2021-02-03 09:07 UTC, d-lazarev commented on ProjectCalendar/Backend/controllers/events.js
> +        const { body: { inputStartDate, inputEndDate, event, created_by } } = req;
You can just use `= req.body` instead of `= req`, to avoid one more nesting

2021-02-03 09:07 UTC, d-lazarev commented on ProjectCalendar/Backend/controllers/events.js
> +        Events.create({ startDate: inputStartDate, endDate: inputEndDate, event: event, created_by: created_by }, function (err, result) {
https://github.com/airbnb/javascript#es6-object-concise

2021-02-03 09:07 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CalendarFormation.js
> +import moment from 'moment';
Why do you just copied-pasted the `createCalendar` function but didn't delete it?

Calendar Formation - is a bad name for the React Component
I don't know what this Component render

2021-02-03 09:07 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                })}
Bad code style, please fix it (https://github.com/airbnb/javascript/tree/master/react#alignment)
Also, remove the commented code

2021-02-03 09:07 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CalendarFormation.js
> +  }
Are you really need this additional handler that just executes a function from the props?

2021-02-03 09:07 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
>            })}
I don't know why this function (`createCalendar`) wasn't deleted

2021-02-03 09:13 UTC, petrukhinilya commented on ProjectCalendar/Backend/controllers/events.js
> +        const { body: { inputStartDate, inputEndDate, event, created_by } } = req;
fixed

2021-02-03 10:33 UTC, petrukhinilya commented on ProjectCalendar/Backend/controllers/events.js
> +        Events.create({ startDate: inputStartDate, endDate: inputEndDate, event: event, created_by: created_by }, function (err, result) {
Fixed

2021-02-03 10:37 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CreateCalendar.js
>            })}
Deleted

2021-02-03 10:40 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CalendarFormation.js
> +import moment from 'moment';
Deleted, and change naming

2021-02-03 10:48 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +                })}
Fixed

2021-02-03 10:49 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CalendarFormation.js
> +  }
Remove this addition func , fixed

2021-02-03 11:53 UTC, d-lazarev approved these changes

2021-02-03 11:53 UTC, merged