Update event
petrukhinilya/Calendar pull request #14
Opened 2021-02-02 08:44 UTC by petrukhinilya

2021-02-03 14:36 UTC, d-lazarev requested changes
Notes

2021-02-03 14:36 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Actions/index.js
> +    let inputEndDate = Number(end);
Always use `const` if you won't change the variable

2021-02-03 14:36 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Actions/index.js
> +    let inputEndDate = Number(new Date(endDate).getTime());
Always use `const` if you won't change the variable

2021-02-03 14:36 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const [changePopup, setChangePopup] = useState(false);
The verb for the boolean variable?

2021-02-03 14:36 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Reducers/events.js
> +
Unnecessary blank line

2021-02-03 14:36 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CalendarDay.js
> +                <div className = 'event'onClick={() => updateEvents(event)}>{event.event}</div>
fix codestyle

2021-02-03 14:40 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Actions/index.js
> +    let inputEndDate = Number(end);
Resolved

2021-02-03 14:41 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Actions/index.js
> +    let inputEndDate = Number(new Date(endDate).getTime());
Resolved

2021-02-03 14:42 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Reducers/events.js
> +
fixed

2021-02-03 14:46 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CalendarDay.js
> +                <div className = 'event'onClick={() => updateEvents(event)}>{event.event}</div>
Fixed

2021-02-03 14:54 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const [changePopup, setChangePopup] = useState(false);
Fixed

2021-02-04 07:19 UTC, d-lazarev requested changes
Notes

2021-02-04 07:19 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const [dayPopup, setDayPopup] = useState(false);
How should I understand for what purpose this variable here and what it does?

2021-02-04 07:19 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Components/Calendar/CalendarDay.js
> +                <div className = 'event' onClick={() => updateEvents(event)}>{event.event}</div>
Codestyle wasn't fixed

2021-02-04 07:49 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/Calendar.js
> +  const [dayPopup, setDayPopup] = useState(false);
Fixed

2021-02-04 07:49 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Components/Calendar/CalendarDay.js
> +                <div className = 'event' onClick={() => updateEvents(event)}>{event.event}</div>
Fixed

2021-02-04 09:35 UTC, d-lazarev approved these changes

2021-02-04 09:55 UTC, merged