Authentication
petrukhinilya/Calendar pull request #16
Opened 2021-02-05 10:15 UTC by petrukhinilya

2021-02-05 17:08 UTC, d-lazarev requested changes
Notes

2021-02-05 17:08 UTC, d-lazarev commented on ProjectCalendar/Backend/routes/events.js
> +};
What's the difference between `queryVerify` and `tokenVerify`?

2021-02-05 17:08 UTC, d-lazarev commented on ProjectCalendar/Backend/routes/events.js
> +};
Move that function-middlewares to a separate file and import them here

2021-02-05 17:08 UTC, d-lazarev commented on ProjectCalendar/Frontend/src/Actions/index.js
> +      body: JSON.stringify({ startDate: inputStartDate, endDate: inputEndDate, event, token })
Hmm, maybe make sense to call the variables as they called on the backend side?
`inputStartDate` -> `startDate`

2021-02-08 07:10 UTC, petrukhinilya commented on ProjectCalendar/Frontend/src/Actions/index.js
> +      body: JSON.stringify({ startDate: inputStartDate, endDate: inputEndDate, event, token })
Resolved

2021-02-08 08:30 UTC, petrukhinilya commented on ProjectCalendar/Backend/routes/events.js
> +};
The main difference that query verify it`s func for req.query in get request

Fixed

2021-02-08 12:59 UTC, d-lazarev requested changes

2021-02-08 12:59 UTC, d-lazarev commented on ProjectCalendar/Backend/middleware/verifyToken.js
> +    queryVerify: (req, res, next) => {
So, I think that you can handle `query` or `body` in a single function, instead of creating 2 functions that have 90% similarity

2021-02-08 14:46 UTC, petrukhinilya commented on ProjectCalendar/Backend/middleware/verifyToken.js
> +    queryVerify: (req, res, next) => {
Resolved

2021-02-09 15:03 UTC, d-lazarev requested changes

2021-02-09 15:03 UTC, d-lazarev commented on ProjectCalendar/Backend/middleware/verifyToken.js
> +        const { token:queryToken } = req.query;
codestyle

2021-02-09 15:03 UTC, d-lazarev commented on ProjectCalendar/Backend/controllers/events.js
> +        const { startDate, endDate, event, id:created_by } = req.body;
codestyle

2021-02-09 15:03 UTC, d-lazarev commented on ProjectCalendar/Backend/controllers/events.js
> +        Events.find({created_by:req.body.id}, function (err, events) {
codestyle

2021-02-09 15:03 UTC, d-lazarev commented on ProjectCalendar/Backend/controllers/events.js
> +        const { startDate, endDate, event, id:created_by } = req.body;
codestyle

2021-02-10 14:00 UTC, petrukhinilya commented on ProjectCalendar/Backend/middleware/verifyToken.js
> +        const { token:queryToken } = req.query;
Fixed

2021-02-10 14:01 UTC, petrukhinilya commented on ProjectCalendar/Backend/controllers/events.js
> +        const { startDate, endDate, event, id:created_by } = req.body;
Fxied

2021-02-10 14:01 UTC, petrukhinilya commented on ProjectCalendar/Backend/controllers/events.js
> +        Events.find({created_by:req.body.id}, function (err, events) {
Fixed

2021-02-10 14:02 UTC, petrukhinilya commented on ProjectCalendar/Backend/controllers/events.js
> +        const { startDate, endDate, event, id:created_by } = req.body;
Fixed

2021-02-16 07:44 UTC, d-lazarev approved these changes

2021-02-16 07:44 UTC, merged